// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using DynamicPermissions.Models;
using DynamicPermissions.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace DynamicPermissions.Data
{
	public partial class DynamicPermissionsContext : IdentityDbContext<ApplicationUser, Role, string>
	{
		public DynamicPermissionsContext()
		{
		}

		public DynamicPermissionsContext(DbContextOptions<DynamicPermissionsContext> options) : base(options)
		{
		}

		public virtual DbSet<ApplicationUser> ApplicationUser { get; set; }

		
		public virtual DbSet<AppValidationSetting> AppValidationSetting { get; set; }


		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			modelBuilder.Entity<IdentityUserLogin<string>>(entity => {
				entity.HasNoKey();
			});

			//modelBuilder.Entity<ApplicationUser>(a => {
			//    a.Property(p=>p.AuthorizorTypeId).HasAnnotation=
			//});
			base.OnModelCreating(modelBuilder);

			//OnModelCreatingPartial(modelBuilder);
			//modelBuilder.Ignore<IdentityUserLogin<string>>();
			//modelBuilder.Ignore<IdentityUserRole<string>>();
			//modelBuilder.Ignore<IdentityUserClaim<string>>();
			//modelBuilder.Ignore<IdentityUserToken<string>>();
			//modelBuilder.Ignore<IdentityUser<string>>();
			//modelBuilder.Ignore<Iden>();
		}



	   
	}
}